name = "vibeflare-mcp-cms"
main = "index.ts"
compatibility_date = "2024-01-01"

# Replace these placeholder IDs with your actual Cloudflare resource IDs
# Run: wrangler kv:namespace create "CONTENT" to get KV ID
# Run: wrangler d1 create vibeflare to get D1 ID  
# Run: wrangler r2 bucket create your-bucket-name to get R2 bucket

kv_namespaces = [
  { binding = "CONTENT", id = "REPLACE_ME_WITH_KV_ID" }
]

d1_databases = [
  { binding = "DB", database_name = "vibeflare", database_id = "REPLACE_ME_WITH_D1_ID" }
]

r2_buckets = [
  { binding = "BUCKET", bucket_name = "REPLACE_ME_WITH_BUCKET_NAME" }
]

# TODO: Add Cloudflare Access authentication for production
# [env.production.vars]
# AUTH_DOMAIN = "your-team.cloudflareaccess.com" 